---
dev_requirements:
  - pylint
  - flake8
  - black
  - ruff
  - mypy
  - isort
  - yamllint

  # For mklocal tasks.
  - yambs
  - vmklib

  # For documentation.
  - sphinx
  - sphinx-book-theme

status: 5 - Production/Stable
