---
dev_requirements:
  - pylint
  - flake8
  - black
  - ruff
  - mypy
  - isort
  - yamllint

  # For workflow tasks.
  - yambs
  - vmklib

  # For documentation.
  - sphinx
  - sphinx-book-theme

status: 5 - Production/Stable

log_format: "%(name)-36s - %(levelname)-6s - %(message)s"
