---
version: "1.0"
xmlns: http://www.w3.org/2000/svg
x_offset: {{x_offset|default(0, true)}}
y_offset: {{y_offset|default(0, true)}}
width: {{width|default(100, true)}}
height: {{height|default(100, true)}}
{% if grid %}
grid:
  color: "{{grid.color|default('black', true)}}"
  lines: {{grid.lines|default(0, true)}}
  width: {{grid.width|default(0, true)}}
{% endif %}
{% if border %}
border:
  color: "{{border.color|default('black', true)}}"
  width: {{border.width|default(0, true)}}
{% endif %}
{% if background %}
background:
  theme: {{background.theme}}
  variant: {{background.variant}}
  hue: {{background.hue}}
{% endif %}
