version: "1.0"
xmlns: http://www.w3.org/2000/svg
{% set _x_offset = x_offset|default(0, true) %}
{% set _y_offset = y_offset|default(0, true) %}
{% set _width = width|default(100, true) %}
{% set _height = height|default(100, true) %}
x1: {{_x_offset}}
y1: {{_y_offset}}
x2: {{_width + _x_offset}}
y2: {{_height + _y_offset}}
width: {{_width}}
height: {{_height}}
grid:
  lines: {{grid.lines|default(0, true)}}
  color: {{grid.color|default("black", true)}}
  width: {{grid.width|default(0, true)}}
border:
  color: {{border.color|default("black", true)}}
  width: {{border.width|default(0, true)}}
background:
  color: "{{background.color}}"
