---
name:
  type: string
version:
  type: string
description:
  type: string
entry:
  type: string
  required: false
setup_args:
  type: list
  schema:
    type: string
  required: false
init_local:
  type: string
  required: false
pypi_name:
  type: string
  required: false
no_chdir_arg:
  type: boolean
  required: false
