name:
  type: string
version:
  type: string
description:
  type: string
setup_args:
  type: list
  schema:
    type: string
  required: false
init_local:
  type: string
  required: false
pypi_name:
  type: string
  required: false
