---
name: Lint YAML

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"

    steps:
      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: install-mk
        run: |
          pip${{matrix.python-version}} install vmklib
      - name: venv
        run: |
          mk PYTHON_VERSION=${{matrix.python-version}} venv
      - name: lint
        run: |
          mk PYTHON_VERSION=${{matrix.python-version}} lint
